apiVersion: v1
kind: Service
metadata:
  name: kayak-service
  labels:
    app: kayak-service
spec:
  ports:
    - name: http
      port: 8000
  selector:
    app: kayak-service
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kayak-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kayak-service
        version: v1
    spec:
      containers:
        - name: kayak-app
          image: gcr.io/spring-boot-gke/kayak-app-auth:1.0
          imagePullPolicy: IfNotPresent
          env:
            - name: MONGODB_HOST
              value: mongodb
          ports:
            - containerPort: 8000
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
